version: 2.1

jobs:
  pre-commit:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:9.0
    steps:
      - checkout
      - run:
          name: Install Python 3 and pip
          command: apt-get update && apt-get install -y python3
      - run:
          name: Install Node
          command: apt-get update && apt-get install -y nodejs npm
      - run:
          name: Install pre-commit
          command: apt-get update && apt-get install -y pre-commit
      - run:
          name: Run pre-commit hooks
          command: pre-commit run --all-files
  backend-tests:
    docker:
      - image: cimg/base
    steps:
      - checkout
      - run:
          name: Run C# tests
          command: docker compose -f compose-tests.yaml up --build

workflows:
  verification-workflow:
    jobs:
      - pre-commit
      - backend-tests
